# -*- coding: utf-8 -*-
# Legal & Informational Pages Content (Contact Us, Terms of Service, Privacy Policy)
# Zero banned words, compliant with Google 2026 E-E-A-T & Privacy Standards

LEGAL_PAGES = {'contact-us': {'title': 'Contact Us | YT4MP3 Support & Feedback',
                'meta_desc': 'Contact YT4MP3 support team for inquiries, feedback, bug reports, and DMCA copyright '
                             'notices regarding our YouTube to MP3 and MP4 converter.',
                'h1': 'Contact YT4MP3',
                'subtitle': 'Have questions, feedback, or a copyright inquiry? Get in touch with our support team.',
                'badge': 'Support & Inquiries',
                'canonical_url': 'https://www.yt4mp3.com/contact-us',
                'article_html': '<p>Welcome to the official YT4MP3 support portal. Our objective is to ensure that '
                                'every visitor enjoys a smooth, reliable, and uninterrupted media conversion '
                                'experience. Whether you have questions regarding our YouTube to MP3 audio converter, '
                                'need advice on saving 1080p or 4K MP4 videos, or wish to report a temporary link '
                                'parsing issue, our dedicated support team is ready to assist you.</p>\n'
                                '\n'
                                '<h3>Primary Communication Channels</h3>\n'
                                '\n'
                                '<p>To ensure prompt and efficient communication, we maintain separate email channels '
                                'for general assistance, system bug reports, and copyright inquiries. Selecting the '
                                'appropriate address ensures your message reaches the correct team member without '
                                'unnecessary delays:</p>\n'
                                '\n'
                                '<div class="contact-box">\n'
                                '  <p><strong>General Support & User Feedback:</strong> support@yt4mp3.com</p>\n'
                                '  <p>Our standard response window is within twenty-four to forty-eight business '
                                'hours, Monday through Friday.</p>\n'
                                '</div>\n'
                                '\n'
                                '<div class="contact-box">\n'
                                '  <p><strong>DMCA, Copyright & Legal Correspondence:</strong> dmca@yt4mp3.com</p>\n'
                                '  <p>Legal and intellectual property matters are reviewed with high priority within '
                                'one business day.</p>\n'
                                '</div>\n'
                                '\n'
                                '<h3>Support Overview and Platform Operation</h3>\n'
                                '\n'
                                '<p>YT4MP3 operates as a client-side and cloud-assisted media transcoding utility. '
                                'When you insert a link into our input form, our automated system queries public media '
                                'sources to identify available audio streams and video containers. All file '
                                'conversions are processed on demand in temporary server buffers and served straight '
                                'to your browser session. We do not maintain public file hosting archives, nor do we '
                                'retain user file conversion records once your session ends.</p>\n'
                                '\n'
                                '<div style="overflow-x: auto; margin: 24px 0;">\n'
                                '<table>\n'
                                '<thead>\n'
                                '<tr>\n'
                                '<th>Inquiry Type</th>\n'
                                '<th>Recommended Department</th>\n'
                                '<th>Average Response Window</th>\n'
                                '</tr>\n'
                                '</thead>\n'
                                '<tbody>\n'
                                '<tr>\n'
                                '<td>Conversion Failure / Link Error</td>\n'
                                '<td>support@yt4mp3.com</td>\n'
                                '<td>24 - 48 Hours</td>\n'
                                '</tr>\n'
                                '<tr>\n'
                                '<td>Feature Request / Suggestions</td>\n'
                                '<td>support@yt4mp3.com</td>\n'
                                '<td>2 - 3 Business Days</td>\n'
                                '</tr>\n'
                                '<tr>\n'
                                '<td>Copyright & DMCA Inquiries</td>\n'
                                '<td>dmca@yt4mp3.com</td>\n'
                                '<td>Within 24 Hours</td>\n'
                                '</tr>\n'
                                '<tr>\n'
                                '<td>Partnership & Press Requests</td>\n'
                                '<td>contact@yt4mp3.com</td>\n'
                                '<td>2 - 4 Business Days</td>\n'
                                '</tr>\n'
                                '</tbody>\n'
                                '</table>\n'
                                '</div>\n'
                                '\n'
                                '<h3>Frequently Encountered Questions and Quick Troubleshooting</h3>\n'
                                '\n'
                                '<p>Before submitting an email ticket, please review the common issues and resolutions '
                                'outlined below. Over ninety percent of user inquiries can be resolved immediately '
                                'with these practical steps:</p>\n'
                                '\n'
                                '<ul>\n'
                                '  <li><strong>Public Video Accessibility:</strong> Confirm that the YouTube link you '
                                'are trying to convert is publicly accessible. Private videos, unlisted media with '
                                'geographical geo-blocks, or age-restricted content that requires a user login cannot '
                                'be fetched by automated converters.</li>\n'
                                '  <li><strong>URL Formatting Check:</strong> Ensure that you paste a clean URL '
                                'string. While our parser accepts standard desktop links, mobile short URLs, and '
                                'YouTube Shorts links, links that include playlist query arguments (such as list= '
                                'parameters) may fail or cause unintended redirection.</li>\n'
                                '  <li><strong>Network Drops and Large File Downloads:</strong> Converting full-length '
                                'concerts, long-duration podcasts, or 4K videos requires consistent bandwidth. If your '
                                'network connection drops midway through processing, the browser download will fail. '
                                'Simply refresh your browser tab, paste the link again, and allow the server to '
                                'reconstruct the media buffer.</li>\n'
                                '  <li><strong>Browser Cache and Extensions:</strong> Aggressive third-party ad '
                                'blockers or privacy extensions occasionally block stream chunks. If a download does '
                                'not trigger, test the link in an incognito or private browsing window without active '
                                'extensions.</li>\n'
                                '</ul>\n'
                                '\n'
                                '<h3>Reporting a System Malfunction or Bug</h3>\n'
                                '\n'
                                '<p>If you encounter a persistent bug or unexpected error code on our website, we '
                                'appreciate your help in filing an informative bug report. Providing clear, specific '
                                'details helps our development team reproduce the problem and deploy a fix quickly. '
                                'When emailing us, please include:</p>\n'
                                '\n'
                                '<ul>\n'
                                '  <li><strong>Target URL:</strong> The specific YouTube video link that caused the '
                                'error.</li>\n'
                                '  <li><strong>Selected Format & Setting:</strong> The conversion option you selected '
                                '(for example, MP3 audio at 320kbps, 256kbps, 128kbps, or MP4 video at 1080p, 720p, or '
                                '4K).</li>\n'
                                '  <li><strong>Device and Operating System:</strong> The device you were using (such '
                                'as a Windows 11 PC, MacBook macOS, Android phone, iPhone iOS, or Chromebook).</li>\n'
                                '  <li><strong>Web Browser Name and Version:</strong> Whether you were running Google '
                                'Chrome, Mozilla Firefox, Apple Safari, Microsoft Edge, or Samsung Internet.</li>\n'
                                '  <li><strong>Error Description:</strong> A brief description of what happened (for '
                                'example, "conversion progress halted at eighty percent" or "received a network '
                                'timeout alert").</li>\n'
                                '</ul>\n'
                                '\n'
                                '<h3>Copyright and DMCA Notification Guidelines</h3>\n'
                                '\n'
                                '<p>YT4MP3 respects the intellectual property rights of content creators, musical '
                                'artists, and production companies. We maintain a zero-tolerance policy toward '
                                'copyright infringement. Our platform functions strictly as an automated transcoding '
                                'tool, and we do not host, store, or index copyrighted materials on permanent '
                                'servers.</p>\n'
                                '\n'
                                '<p>If you are a copyright owner or an authorized agent representing a copyright '
                                'owner, and you believe that our web tool is being misused in relation to your '
                                'intellectual property, please submit a formal notification to '
                                '<strong>dmca@yt4mp3.com</strong> containing the following statutory elements:</p>\n'
                                '\n'
                                '<ul>\n'
                                '  <li>A physical or electronic signature of a person authorized to act on behalf of '
                                'the copyright owner.</li>\n'
                                '  <li>Identification of the copyrighted work claimed to have been infringed, or a '
                                'representative list of such works.</li>\n'
                                '  <li>Specific identification of the material and the exact URL paths that form the '
                                'basis of your notice.</li>\n'
                                '  <li>Adequate contact information, including your full legal name, physical mailing '
                                'address, telephone number, and official email address.</li>\n'
                                '  <li>A statement that you have a good faith belief that use of the material in the '
                                'manner complained of is not authorized by the copyright owner, its agent, or the '
                                'law.</li>\n'
                                '  <li>A statement made under penalty of perjury that the information in the '
                                'notification is accurate and that you are authorized to act on behalf of the '
                                'owner.</li>\n'
                                '</ul>\n'
                                '\n'
                                '<h3>Commitment to User Privacy and Security</h3>\n'
                                '\n'
                                '<p>When you reach out to our support staff via email, we use your contact details '
                                'solely to reply to your inquiry and resolve your issue. We never sell, rent, or share '
                                'user email addresses with external advertisers or commercial data brokers. Once an '
                                'inquiry is resolved and closed, support correspondence is archived securely in '
                                'accordance with our data protection policies.</p>\n'
                                '\n'
                                '<p>Thank you for choosing YT4MP3. We value your feedback and remain committed to '
                                'maintaining the fastest, cleanest, and most accessible media conversion tool on the '
                                'web.</p>'},
 'terms-of-service': {'title': 'Terms of Service | YT4MP3 Online Converter',
                      'meta_desc': 'Review the Terms of Service for using YT4MP3 YouTube to MP3 and MP4 converter. '
                                   'Understand usage guidelines, copyright policies, and service terms.',
                      'h1': 'Terms of Service',
                      'subtitle': 'Please read these terms carefully before using our online video and audio '
                                  'conversion tool.',
                      'badge': 'Legal Terms',
                      'canonical_url': 'https://www.yt4mp3.com/terms-of-service',
                      'article_html': '<h2>Terms of Service</h2>\n'
                                      '\n'
                                      '<p>Welcome to <strong>https://www.yt4mp3.com/</strong>. By accessing or '
                                      'utilizing our web-based video conversion utility, you agree to comply with and '
                                      'be bound by the following terms and conditions. Please review these provisions '
                                      'carefully before using our platform. If you do not agree with any part of these '
                                      'rules, you must immediately cease all usage of our services.</p>\n'
                                      '\n'
                                      '<h3>1. Acceptance of Terms</h3>\n'
                                      '\n'
                                      '<p>By accessing, browsing, or utilizing '
                                      '<strong>https://www.yt4mp3.com/</strong>, you acknowledge that you have read, '
                                      'understood, and agreed to be legally bound by these Terms of Service. These '
                                      'rules apply to all visitors, users, and others who access the web tool. We '
                                      'reserve the right to modify, amend, or update these terms at any time without '
                                      'prior notice. Your continued use of the platform following any modifications '
                                      'indicates your acceptance of the revised conditions.</p>\n'
                                      '\n'
                                      '<h3>2. Permitted Personal Use</h3>\n'
                                      '\n'
                                      '<p>Our web tool is provided strictly for personal, non-commercial use. When '
                                      'utilizing our online video converter to process media from YouTube or other '
                                      'supported platforms, you agree to adhere to the following behavioral '
                                      'standards:</p>\n'
                                      '\n'
                                      '<ul>\n'
                                      '    <li>You must only download and convert content for which you possess the '
                                      'explicit legal rights, ownership, or proper authorization from the copyright '
                                      'holder.</li>\n'
                                      '    <li>You are solely responsible for ensuring that your actions do not '
                                      'violate the terms of service of the source platforms or infringe upon '
                                      'applicable intellectual property laws.</li>\n'
                                      '    <li>You may not use our platform to redistribute, sell, lease, or '
                                      'commercially exploit any converted media files obtained through our '
                                      'system.</li>\n'
                                      '    <li>You shall not employ automated scripts, bots, or scrapers to abuse the '
                                      'functionality of our conversion infrastructure.</li>\n'
                                      '</ul>\n'
                                      '\n'
                                      '<h3>3. Intellectual Property and Copyright</h3>\n'
                                      '\n'
                                      '<p>We respect the intellectual property rights of creators, artists, and '
                                      'copyright holders. <strong>https://www.yt4mp3.com/</strong> operates strictly '
                                      'as a neutral utility that allows users to transcode media files based on direct '
                                      'user instruction.</p>\n'
                                      '\n'
                                      '<p><strong>DMCA Compliance:</strong> We do not tolerate copyright infringement '
                                      'on our platform. If you believe any content processed through our service '
                                      'infringes your copyright, please send us a formal DMCA notice. Your notice must '
                                      'identify the copyrighted work, include your contact information, and contain a '
                                      'statement of authorization.</p>\n'
                                      '\n'
                                      '<h3>4. Service Availability</h3>\n'
                                      '\n'
                                      '<p><strong>https://www.yt4mp3.com/</strong> is offered to the public as a free '
                                      'online service. Currently, we do not enforce daily conversion limits, allowing '
                                      'users to convert media files freely. However, please note the following '
                                      'operational parameters:</p>\n'
                                      '\n'
                                      '<ul>\n'
                                      '    <li>The service is provided on an "as-is" and "as-available" basis without '
                                      'warranties of any kind, either express or implied.</li>\n'
                                      '    <li>We do not guarantee uninterrupted, continuous, or secure access to our '
                                      'web tool. Maintenance, updates, or external network failures may cause '
                                      'temporary service disruptions.</li>\n'
                                      '    <li>We reserve the right to modify, suspend, or discontinue the service—or '
                                      'impose usage restrictions and daily conversion limits—at any time and without '
                                      'prior notice.</li>\n'
                                      '</ul>\n'
                                      '\n'
                                      '<h3>5. Third-Party Content Disclaimer</h3>\n'
                                      '\n'
                                      '<p>Our platform does not host, store, or archive any audio or video files on '
                                      'its servers. <strong>https://www.yt4mp3.com/</strong> functions merely as an '
                                      'automated cloud transcoding utility that processes media streams in real-time '
                                      'based solely on user requests.</p>\n'
                                      '\n'
                                      '<ul>\n'
                                      '    <li>All video and audio content accessed, converted, or downloaded through '
                                      'our interface remains the sole property of the respective content creators and '
                                      'third-party platforms.</li>\n'
                                      '    <li>We have no control over, and assume no responsibility for, the content, '
                                      'privacy policies, or practices of any third-party websites or services linked '
                                      'to or associated with the source media.</li>\n'
                                      '    <li>Temporary cloud processing files generated during the conversion '
                                      'session are automatically purged from our system infrastructure shortly after '
                                      'the transcoding process finishes.</li>\n'
                                      '</ul>\n'
                                      '\n'
                                      '<h3>6. Limitation of Liability</h3>\n'
                                      '\n'
                                      '<p>To the fullest extent allowed by law, YT4MP3 and its operators will not be '
                                      'liable for any damages resulting from using or being unable to use our '
                                      'tool.</p>\n'
                                      '\n'
                                      '<p>This limitation applies to any damages or injuries arising from:</p>\n'
                                      '\n'
                                      '<ul>\n'
                                      '    <li>Errors, mistakes, or inaccuracies of content processed through the '
                                      'service.</li>\n'
                                      '    <li>Unauthorized access to or use of our servers and any personal '
                                      'information stored therein.</li>\n'
                                      '    <li>Any interruption or cessation of transmission to or from our web '
                                      'platform.</li>\n'
                                      '    <li>Any bugs, viruses, Trojan horses, or similar malicious code that may be '
                                      'transmitted to or through our service by any third party.</li>\n'
                                      '    <li>Any legal liabilities, copyright penalties, or claims brought against '
                                      'you by third-party platforms or copyright holders due to unauthorized file '
                                      'conversion or retention.</li>\n'
                                      '</ul>\n'
                                      '\n'
                                      '<p>Your sole remedy for dissatisfaction with the service is to stop using the '
                                      'platform immediately. If you have any questions regarding these terms, please '
                                      'contact our support department through the designated channels available on our '
                                      'website.</p>'},
 'privacy-policy': {'title': 'Privacy Policy | YT4MP3 User Privacy & Data Protection',
                    'meta_desc': 'Learn how YT4MP3 protects your privacy. We do not require account registration or '
                                 'store personal conversion history.',
                    'h1': 'Privacy Policy',
                    'subtitle': 'Our commitment to user privacy, data security, and transparent processing practices.',
                    'badge': 'Privacy & Security',
                    'canonical_url': 'https://www.yt4mp3.com/privacy-policy',
                    'article_html': '<h2>Privacy Policy for YT4MP3.com</h2>\n'
                                    '\n'
                                    '<p>Welcome to YT4MP3.com. We respect your privacy and are committed to protecting '
                                    'your personal data when you use our online media conversion tools. This privacy '
                                    'document outlines how we handle information related to your visit and use of our '
                                    'platform. By accessing or using YT4MP3.com, you agree to the practices described '
                                    'in this policy.</p>\n'
                                    '\n'
                                    '<h3>Privacy Commitment</h3>\n'
                                    '\n'
                                    '<p>At YT4MP3.com, we believe that converting media should be straightforward and '
                                    'private. We have designed our system so that you can convert YouTube videos to '
                                    'MP3 and MP4 formats without needing to create an account. No registration or '
                                    'personal sign-up is required to access our core features. You do not need to '
                                    'provide an email address, username, or password to use our tools. This anonymous '
                                    'approach ensures that your media conversion activities remain entirely '
                                    'confidential.</p>\n'
                                    '\n'
                                    '<h3>Information Not Collected</h3>\n'
                                    '\n'
                                    '<p>Because user privacy is central to our service, we deliberately avoid '
                                    'gathering sensitive data. We do not collect names, email addresses, credit card '
                                    'details, billing addresses, or any other form of personally identifiable '
                                    'information. Since financial transactions are not part of our platform, payment '
                                    'details are never requested, stored, or processed by our servers. You remain '
                                    'anonymous while interacting with our conversion tools, and we do not build user '
                                    'profiles based on personal identity.</p>\n'
                                    '\n'
                                    '<h3>Automatic Server Logs</h3>\n'
                                    '\n'
                                    '<p>To maintain platform security, prevent abuse, and ensure reliable server '
                                    'performance, our web infrastructure automatically records certain standard system '
                                    'details when you visit YT4MP3.com. These server logs may include:</p>\n'
                                    '<ul>\n'
                                    '    <li>Anonymized IP addresses</li>\n'
                                    '    <li>Browser type and version</li>\n'
                                    '    <li>Operating system information</li>\n'
                                    '    <li>Timestamps of requests</li>\n'
                                    '    <li>Referring web pages</li>\n'
                                    '</ul>\n'
                                    '<p>Please note that IP addresses recorded in our server logs are anonymized to '
                                    'prevent direct association with individual users. This data is used strictly for '
                                    'system administration, traffic analysis, and safeguarding our infrastructure '
                                    'against malicious attacks or automated scraping.</p>\n'
                                    '\n'
                                    '<h3>Temporary Processing</h3>\n'
                                    '\n'
                                    '<p>When you input a URL to convert a video into MP3 or MP4 format, our system '
                                    'processes the media stream in temporary server memory (RAM). This processing '
                                    'occurs strictly on an as-needed basis to deliver the requested file directly to '
                                    'your device. We do not maintain a permanent archive of the media files you '
                                    'convert. Once the conversion process finishes and the file is delivered to your '
                                    'browser, the temporary data is purged automatically from our memory and storage '
                                    'caches. We do not store copies of converted audio or video files on our '
                                    'servers.</p>\n'
                                    '\n'
                                    '<h3>Cookies and Security</h3>\n'
                                    '\n'
                                    '<p>YT4MP3.com utilizes a secure HTTPS connection across all pages. This encryption '
                                    'ensures that data transmitted between your browser and our servers remains '
                                    'private and protected from interception by third parties. Regarding cookies, we '
                                    'do not employ tracking cookies or invasive analytics tools that follow your '
                                    'browsing habits across external websites. Any small data files placed on your '
                                    'device are strictly functional, serving to maintain session stability and proper '
                                    'website operation.</p>\n'
                                    '\n'
                                    '<h3>User Rights and Policy Changes</h3>\n'
                                    '\n'
                                    '<p>Because we do not collect or store personal information, we generally do not '
                                    'hold identifiable data that can be accessed, modified, or deleted upon request. '
                                    'If you have questions regarding our privacy practices, you may reach out through '
                                    'our designated contact channels. We reserve the right to update this privacy '
                                    'policy periodically to reflect changes in our services or legal obligations. Any '
                                    'modifications will be posted directly on this page, and continued use of '
                                    'YT4MP3.com constitutes your acceptance of the revised terms.</p>'}}
